CREATE DATABASE db;

CREATE TABLE IF NOT EXISTS users
( id INTEGER NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(128) NOT NULL,
  lastName VARCHAR(128) NOT NULL,
  phoneNumber VARCHAR(128) NOT NULL,
  PRIMARY KEY (id)
);

